// test/transcription/crepe_ort_parity_test.dart
//
// END-TO-END parity: the FULL Dart `crepeF0` pipeline vs onnxruntime (ORT).
//
// The reference (crepe_ort_e2e_ref.json) is generated by running a fixed 16 kHz
// signal through torchcrepe's framing → *onnxruntime* (crepe-tiny.onnx) → the
// dither-free weighted_argmax decode. This test regenerates the identical audio
// (same formula), runs it through our `crepeF0` — which frames + normalises in
// Dart, infers on `onnx_runtime_dart`, and decodes in Dart — and asserts the F0
// track matches ORT frame-for-frame. It pins that our framing/normalisation AND
// the pure-Dart engine together reproduce the ORT pipeline, not just the model
// tensor or the decoder in isolation.
//
// Model-gated: skips if the CREPE model can't be provisioned (offline).
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:comet_beat/core/audio/transcription/crepe.dart';
import 'package:comet_beat/core/audio/transcription/crepe_model_store.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:onnx_runtime_dart/onnx_runtime_dart.dart';

Future<OnnxModel?> _tryModel() async {
  final home = Platform.environment['HOME'] ?? '';
  for (final dir in [
    if (home.isNotEmpty) '$home/.cache/onnx_runtime_dart_models',
    null,
  ]) {
    try {
      return await CrepeModelStore(cacheDirOverride: dir).load();
    } catch (_) {
      // try next
    }
  }
  return null;
}

void main() {
  test('crepeF0 reproduces the onnxruntime pipeline frame-for-frame', () async {
    final model = await _tryModel();
    if (model == null) {
      // ignore: avoid_print
      print('SKIP: CREPE model unavailable — skipping ORT parity.');
      return;
    }

    final ref = jsonDecode(
      File('test/transcription/crepe_ort_e2e_ref.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    final sr = ref['sampleRate'] as int;
    final segs =
        (ref['segments'] as List).map((e) => (e as List).cast<num>()).toList();
    final refF0 = (ref['f0Hz'] as List).cast<num>();
    final refVoiced = (ref['voiced'] as List).cast<num>();

    // Regenerate the EXACT reference audio: concatenated pure tones, phase reset
    // per segment — identical to the Python generator.
    final parts = <Float64List>[];
    for (final s in segs) {
      final f = s[0].toDouble();
      final n = (sr * s[1].toDouble()).round();
      final seg = Float64List(n);
      for (var i = 0; i < n; i++) {
        seg[i] = 0.5 * sin(2 * pi * f * i / sr);
      }
      parts.add(seg);
    }
    final audio = Float64List(parts.fold<int>(0, (a, p) => a + p.length));
    var off = 0;
    for (final p in parts) {
      audio.setAll(off, p);
      off += p.length;
    }

    final track = crepeF0(audio, model: model, sampleRate: sr);

    // Same frame count as ORT (framing parity).
    expect(
      track.length,
      refF0.length,
      reason: 'frame count ${track.length} vs ORT ${refF0.length}',
    );

    // Frame-for-frame F0 + voicing parity. Any gap between onnx_runtime_dart and
    // onnxruntime (max|Δ|~3e-7 at the tensor) shows up here as F0 drift.
    var maxDf = 0.0, maxDv = 0.0;
    for (var i = 0; i < track.length; i++) {
      maxDf = max(maxDf, (track[i].f0Hz - refF0[i].toDouble()).abs());
      maxDv = max(maxDv, (track[i].voicedProb - refVoiced[i].toDouble()).abs());
    }
    // ignore: avoid_print
    print('ORT parity over ${track.length} frames: '
        'max|Δf0|=${maxDf.toStringAsFixed(6)} Hz, '
        'max|Δvoiced|=${maxDv.toStringAsFixed(6)}');

    expect(maxDf, lessThan(0.5), reason: 'max f0 drift vs ORT: $maxDf Hz');
    expect(maxDv, lessThan(0.01), reason: 'max voicing drift vs ORT: $maxDv');
  });
}
